from dotenv import load_dotenv
load_dotenv()
import os
from functools import wraps
from datetime import datetime
from flask import Flask, request, jsonify, session, redirect, render_template
import requests
from models import db, Trade, MonthlySummary
import json


REQUEST_TIMEOUT = 10  # seconds — prevents a stalled Coinbase call from hanging the server

# Coins to exclude from the gainers list outright (was BLACKLIST + Gemini haram calls).
# Pulled from your halal_cache.json's confirmed "haram"/"likely haram" entries.
# Add to this manually as you spot new ones — no API call, no lookup delay.
EXCLUDED_SYMBOLS = {
    # meme coins
    "PUMP", "MOG", "USELESS", "SPX", "BONK", "KEYCAT", "TROLL", "BIRB",
    "CLANKER", "TURBO", "FUN1", "PENGU", "DOGINME", "TRUMP", "BASECAT",
   
    # perpetuals / leveraged derivatives
    "DRV", "PERP","DRIFT","HYPE",
    # yield/staking-as-interest edge cases
    "ARB","DRB", "CTX","VELO", "KAIO",
    # legacy blacklist from before
    "PIRATE", "THQ",
}

HALAL_CACHE_PATH = "halal_cache.json"

def load_halal_cache():
    try:
        with open(HALAL_CACHE_PATH, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}

def save_halal_cache(cache):
    with open(HALAL_CACHE_PATH, "w") as f:
        json.dump(cache, f, indent=2)

HALAL_CACHE = load_halal_cache()

from google import genai
from google.genai import types

_genai_client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

def classify_halal(symbol, name):
    if symbol in HALAL_CACHE:
        return HALAL_CACHE[symbol]

    prompt = f"""You are an Islamic-finance cryptocurrency screening engine.

Coin: {name} ({symbol})

Your task is to classify the cryptocurrency as exactly one of:
- "halal"
- "haram"
- "unclear"

Use a strict Shariah screening framework.

IMPORTANT:
Do not classify a coin as haram merely because it has staking, rewards, yield, locking, emissions, or DeFi integrations. Determine WHAT THE REWARD OR RETURN ACTUALLY REPRESENTS and WHERE THE MONEY OR TOKENS COME FROM.

1. CORE UTILITY

Determine what the token actually does:
- What is the token used for?
- Does it have genuine technological, payment, infrastructure, governance, or service utility?
- Is it primarily a meme/speculative token with no meaningful utility?

A pure meme/speculation token with no meaningful utility should generally be treated as a Shariah concern.

2. RIBA / INTEREST

Look specifically for:
- lending and borrowing
- interest paid to lenders or depositors
- fixed or predetermined returns for lending capital
- money deposited with a protocol in exchange for additional money primarily because of time
- interest-bearing stablecoin mechanisms
- lending markets
- debt-based yield
- fixed returns that represent interest on a loan

IMPORTANT:
Do NOT automatically treat every APR, APY, staking reward, yield, or token emission as interest.

For every reward mechanism, determine its actual source.

A. If:
capital is lent or borrowed -> the borrower owes an increase -> the lender/depositor receives that increase

then this is a direct riba concern.

B. If:
tokens are staked or delegated -> a validator, operator, or network participant performs actual work or provides security/service -> protocol or network rewards are distributed

this is NOT automatically riba. Analyze it as a network/service reward.

C. If:
users pay fees for an actual technological service -> operators or participants receive a portion of those fees

this is generally a service/revenue reward rather than interest.

D. If the reward source cannot be established with reasonable confidence, classify the relevant mechanism as unclear rather than assuming it is halal.

3. STAKING

Do not treat "staking" itself as haram.

Determine:
- What exactly is being staked?
- Why is it being staked?
- What does the staker provide?
- Who pays the reward?
- Where do the rewards originate?
- Are rewards generated by network fees, actual services, validator work, protocol revenue, inflation/emissions, or lending/interest?
- Is there slashing or genuine network/security risk?
- Is the return simply payment for time-locking or lending capital?

Distinguish genuine network/security rewards from interest-bearing deposits.

4. DEFI

Check whether the coin's OWN PROTOCOL or ecosystem natively provides:
- lending
- borrowing
- interest-bearing deposits
- leveraged trading
- perpetual futures
- margin trading
- options
- synthetic debt products
- other clearly impermissible financial mechanisms

IMPORTANT:
Do not automatically classify the underlying token as haram merely because THIRD-PARTY protocols can use the token for lending, borrowing, leverage, or other impermissible activities.

Distinguish:
A. functionality intrinsic to the token or native protocol
from
B. unrelated third-party applications that merely support or use the token.

5. LEVERAGE / DERIVATIVES

Check whether the token itself is fundamentally a:
- perpetual futures token
- leveraged trading product
- derivative
- synthetic financial instrument
- margin/leverage-only asset

If the token's primary purpose is an impermissible derivative or leverage product, classify accordingly.

Do not classify a normal utility token as haram merely because exchanges offer futures or perpetuals on that token.

6. GAMBLING / PREDICTION MARKETS

Check for:
- casino or gambling functionality
- betting
- prediction markets
- lotteries
- wagering
- games primarily based on monetary chance

If gambling is intrinsic to the token's primary protocol function, this is a major haram factor.

Do not classify a normal blockchain token as haram merely because unrelated third parties can gamble with it.

7. MEME / PURE SPECULATION

Determine whether the token has:
- meaningful utility
- an actual protocol or service
- infrastructure use
- payment function
- governance utility
- productive economic purpose

If it is essentially a pure meme/speculation asset with no meaningful utility, flag it as a major Shariah concern.

8. OTHER SHARIAH CONCERNS

Also check for:
- clearly prohibited business activity
- fraud or scam characteristics
- excessive gharar or extreme contractual uncertainty
- tokenomics designed primarily around gambling or speculation
- prohibited underlying assets or services
- mechanisms whose economic substance is clearly equivalent to interest

Do not invent concerns merely because the project is complex.

9. ECOSYSTEM VS TOKEN

Separate the following:

A. The token itself
B. The token's native protocol
C. Native staking and reward mechanisms
D. Native financial mechanisms
E. Third-party applications built on or interacting with the protocol

A third-party application using a token does NOT automatically make the token itself haram.

However, if the questionable mechanism is built directly into the token's native protocol or is a necessary/core component of how the token functions, treat it as part of the token's screening.

10. REWARD-SOURCE TRACE

Whenever you see words such as:
- yield
- APR
- APY
- staking rewards
- rewards
- interest
- earn
- locking
- restaking

DO NOT stop at the label.

Trace the economic mechanism:

WHO PROVIDES THE REWARD?
-> WHERE DOES THE REWARD COME FROM?
-> WHAT ECONOMIC ACTIVITY GENERATES IT?
-> IS THERE A LOAN OR DEBT?
-> IS THE RETURN CAUSED BY TIME ON CAPITAL?
-> OR IS IT PAYMENT FOR ACTUAL SERVICE, NETWORK SECURITY, VALIDATION, COMPUTATION, TRANSACTION FEES, OR PROTOCOL REVENUE?

Only classify something as riba when the economic mechanism actually represents interest or a debt-based return.

For example:

"stake/delegate tokens -> provide network security or service -> network generates fees -> participants receive a portion of those fees"

should be analyzed as a network/service reward, NOT automatically as interest.

By contrast:

"deposit tokens -> protocol lends the tokens to borrowers -> borrowers pay interest -> depositor receives a return"

is a direct riba concern.

11. EVIDENCE STANDARD

For a real classification, prioritize:
- current official documentation
- current smart contracts
- current protocol architecture
- current staking/reward contracts
- current reward mechanisms
- on-chain reward flows where available

Do not rely solely on exchange descriptions or generic websites.

If the relevant mechanism cannot be determined with reasonable confidence, classify it as "unclear."

12. CLASSIFICATION RULE

"HARAM":
Use only when there is a clear, intrinsic, or materially central prohibited mechanism such as:
- interest or lending-based return
- gambling or betting
- intrinsic perpetual, derivative, or leverage functionality
- clearly prohibited core business
- another clearly impermissible core mechanism

"HALAL":
Use when:
- the token has legitimate utility,
- no intrinsic prohibited core mechanism is identified,
- staking or rewards, if present, are traceable to legitimate network, service, security, or protocol activity rather than interest,
- questionable activities are only unrelated third-party uses,
- and there is sufficient evidence to understand the relevant mechanisms.

"UNCLEAR":
Use when:
- the economic mechanism cannot be established,
- reward sources are ambiguous,
- the protocol combines permissible and questionable mechanisms in a way that cannot be separated confidently,
- or there is insufficient current evidence.

IMPORTANT FINAL RULE:
Do NOT equate:
- staking = interest
- yield = interest
- APR = interest
- rewards = interest
- locking = interest
- DeFi integration = haram

Instead, determine the actual economic substance.

FINAL OUTPUT:
Respond ONLY with valid JSON in exactly this format:

{{"status": "halal|haram|unclear", "reason": "one short sentence explaining the decisive reason."}}
"""
    try:
        response = _genai_client.models.generate_content(
            model="gemini-3.1-flash-lite",
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json"
            ),
        )

        result = json.loads(response.text)

        if result.get("status") not in ("halal", "haram", "unclear"):
            result["status"] = "unclear"

    except Exception as e:
        print(f"Halal classification failed for {symbol}: {e}")
        result = {
            "status": "unclear",
            "reason": "Classification unavailable right now."
        }

    HALAL_CACHE[symbol] = result
    save_halal_cache(HALAL_CACHE)
    return result


def safe_float(val):
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


app = Flask(__name__)

app.secret_key = os.environ["SECRET_KEY"]
db_url = os.environ["DATABASE_URL"]
if db_url.startswith("postgres://"):
    db_url = db_url.replace("postgres://", "postgresql://", 1)
app.config["SQLALCHEMY_DATABASE_URI"] = db_url
db.init_app(app)

with app.app_context():
    db.create_all()

def require_login(f):
    @wraps(f)
    def wrapper(*a, **kw):
        if not session.get("authed"):
            if request.path.startswith("/api/"):
                return jsonify({"error": "unauthorized"}), 401
            return redirect("/login")
        return f(*a, **kw)
    return wrapper

ALLOWED_TRADE_FIELDS = {
    "session", "coin", "direction", "setup", "sl", "tp", "rr", "pnl",
    "rules_followed", "reason", "confluences", "thesis",
    "what_happened", "better", "lesson", "entry_type", "notes"
}

@app.post("/login")
def login():
    data = request.get_json(silent=True) or {}
    password = data.get("password") or request.form.get("password")
    if password == os.environ["APP_PASSWORD"]:
        session["authed"] = True
        session.permanent = True
        return "", 204
    return "wrong password", 401

@app.get("/api/trades")
@require_login
def list_trades():
    q = Trade.query
    if request.args.get("year") and request.args.get("month"):
        y, m = int(request.args["year"]), int(request.args["month"])
        q = q.filter(db.extract('year', Trade.date) == y,
                     db.extract('month', Trade.date) == m)
    trades = q.order_by(Trade.date.desc()).all()
    return jsonify([t.to_dict() for t in trades])

@app.post("/api/trades")
@require_login
def create_trade():
    data = request.json
    fields = {k: v for k, v in data.items() if k in ALLOWED_TRADE_FIELDS}
    trade = Trade(date=datetime.fromisoformat(data["date"]).date(), **fields)
    db.session.add(trade)
    db.session.commit()
    return jsonify(trade.to_dict()), 201

@app.put("/api/trades/<int:id>")
@require_login
def update_trade(id):
    trade = Trade.query.get_or_404(id)
    for k, v in request.json.items():
        if k == "date":
            setattr(trade, "date", datetime.fromisoformat(v).date())
        elif k in ALLOWED_TRADE_FIELDS:
            setattr(trade, k, v)
    db.session.commit()
    return jsonify(trade.to_dict())

@app.delete("/api/trades/<int:id>")
@require_login
def delete_trade(id):
    Trade.query.filter_by(id=id).delete()
    db.session.commit()
    return "", 204

@app.route("/")
@require_login
def home():
    return render_template("Rules.html")


@app.route("/index")
@require_login
def index():
    return render_template("index.html")


@app.route("/calendar")
@require_login
def calendar():
    return render_template("Calendar.html")

@app.route("/chart")
@require_login
def chart():
    return render_template("Chart.html")

@app.route("/contract")
@require_login
def contract():
    return render_template("Contract.html")

@app.route("/journal")
@require_login
def journal():
    return render_template("sheets.html")

@app.get("/login")
def login_page():
    return render_template("login.html")


@app.route("/api/sparkline/<symbol>")
def sparkline(symbol):
    try:
        resp = requests.get(
            f"https://api.exchange.coinbase.com/products/{symbol}-USD/candles",
            params={"granularity": 3600},  # 1 candle per hour
            headers={"User-Agent": "TC-App"},
            timeout=REQUEST_TIMEOUT
        )
        candles = resp.json()  # newest-first: [time, low, high, open, close, volume]
        closes = [c[4] for c in reversed(candles[:24])]  # last 24h, oldest→newest
        return {"symbol": symbol, "closes": closes}
    except Exception as e:
        print(f"Sparkline fetch failed for {symbol}: {e}")
        return {"symbol": symbol, "closes": []}

@app.route("/api/gainers")
def gainers():
    try:
        response = requests.get(
            "https://api.coinbase.com/api/v3/brokerage/market/products",
            timeout=REQUEST_TIMEOUT
        )
        data = response.json()
        products = data["products"]

        filtered = [
            p for p in products
            if p["product_type"] == "SPOT"
            and p["quote_currency_id"] == "USD"
            and p["trading_disabled"] == False
            and p["is_disabled"] == False
            and p["base_currency_id"] not in EXCLUDED_SYMBOLS
            and safe_float(p.get("price_percentage_change_24h")) is not None
        ]

        sorted_products = sorted(
            filtered,
            key=lambda p: float(p["price_percentage_change_24h"]),
            reverse=True
        )

        top_20 = sorted_products[:20]
        cleaned = []

        for p in top_20:
            symbol = p["base_currency_id"]
            name = p["base_name"]
            halal = classify_halal(symbol, name)  


            cleaned.append({
                "name": name,
                "symbol": symbol,
                "price": p["price"],
                "change_24h": round(float(p["price_percentage_change_24h"]), 2),
                "volume_24h": round(safe_float(p.get("volume_24h")) or 0, 2),
                "halal_status": halal["status"],
                "halal_reason": halal["reason"],
            })

        return cleaned

    except Exception as e:
        print(f"Gainers fetch failed: {e}")
        return []


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    debug_mode = os.getenv("FLASK_DEBUG", "false").lower() == "true"
    app.run(host="0.0.0.0", port=port, debug=debug_mode)